[package]
name = "libdng"
version = "0.1.0"
authors = ["Christopher Schmidt <schmidtc@cs.uni-bonn.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
version = "3.0.0"

[build-dependencies]
cmake = "0.1.45"
